### PR TITLE
updates for datasource problem

### PR DESCRIPTION
**Pull request by ryan2049**

### CODE REVIEW

**Review by soasathish — COMMENTED** [review]
after merging your pull request I am getting the below error while running the application 
5:35:13.783 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at uk.gov.iebr.batch.IEBRFileProcessorApplication.main(IEBRFileProcessorApplication.java:19)
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
	... 8 common frames omitted

**Comment by soasathish** [comment]
Is there any online example .Spring batch using spring data JPA .. I don't see any example with RespositoryItemreader and RepositoryItemWriter on the Internet and books online

**Comment by ryan2049** [comment]
I'm at work.  I won't be able to help till I get home.

**Comment by soasathish** [comment]
Hi Ryan,
Any update on the example ..much appreciate your help in this regard

**Comment by ryan2049** [comment]
Sorry for the delay.  Here is an example of something I was working on that showcases what you asked for.  https://github.com/ryan2049/spring-boot-samples/tree/master/spring-boot-sample-batch/multithreaded-migration

**Pull request merged**
